version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
permissions:
  - object: scripts/stop_server.sh
    pattern: "755"
    owner: root
    group: root
    type: file
  - object: scripts/remove_files.sh
    pattern: "755"
    owner: root
    group: root
    type: file
  - object: scripts/install_dependencies.sh
    pattern: "755"
    owner: root
    group: root
    type: file
  - object: scripts/start_server.sh
    pattern: "755"
    owner: root
    group: root
    type: file
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/remove_files.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
